### ISSUE TITLE
Can `encryptECIES()` take a Buffer as input?

### ISSUE THREAD

**Issue by vsund** [ntzwrk/blockstack.ts#10]
In https://github.com/ntzwrk/blockstack.ts/commit/ae6bc6015fe2e3c5edbb414badc2f74c97e2b7b2 I fixed a potential doubly buffered input (`content` can be either `string` or `Buffer`, but the constructor of `Buffer` only takes `string` as input type).
Wondering now what would happen if `new Buffer()` gets a `Buffer` as input. Should we fix this in `blockstack.js` or does this work?

**Comment by vsund** [comment]
Fixed an error with this solution in https://github.com/ntzwrk/blockstack.ts/commit/d677b248e257ff861bd004c042fa5fe17fa5de2a

**Comment by kantai** [comment]
It's deprecated (like other Buffer constructors), but Buffers _can_ take buffers as inputs. It just makes a copy: https://nodejs.org/api/buffer.html#buffer_new_buffer_buffer

**Comment by vsund** [comment]
Ah ok, thanks! Since it's deprecated, should I raise a PR against `blockstack.js` or leave it as it is?

**Comment by kantai** [comment]
You can raise a PR -- should be a pretty direct conversion to just using the `Buffer.from()`

**Comment by vsund** [comment]
Thanks, did so: https://github.com/blockstack/blockstack.js/pull/395
