### ISSUE TITLE
Clarify whether `getGracePeriod()` needs a parameter or not

### ISSUE THREAD

**Issue by vsund** [ntzwrk/blockstack.ts#7]
Hey @kantai, the [`getGracePeriod()`](https://github.com/blockstack/blockstack.js/blob/286df82401c5be8d89e352054e2192e0f600ea98/src/network.js#L61) in `src/network.js` doesn't take a parameter according to the implementation there.
But in [`src/operations/safety.js`](https://github.com/blockstack/blockstack.js/blob/286df82401c5be8d89e352054e2192e0f600ea98/src/operations/safety.js#L56) you pass the `fullyQualifiedName` through to `getGracePeriod()`.

Does `getGracePeriod()` needs the name as parameter? I currently assume yes, in case the grace period depends on the namespace (see commit https://github.com/ntzwrk/blockstack.ts/commit/329c6a601bf67380eaa5ed6b9122e075802f33e6).

**Comment by kantai** [comment]
Currently doesn't need the name as a parameter.

**Comment by vsund** [comment]
Removed it in d37794572d299111e8150fdaabeef65a44ce4841 from that call.
Should I remove the parameter upstream in `src/operations/safety.js` too?

**Comment by vsund** [comment]
Solved in https://github.com/ntzwrk/blockstack.ts/commit/d37794572d299111e8150fdaabeef65a44ce4841. If I should fix this in `blockstack.js` leave me a message @kantai :)
