### ISSUE TITLE
Clarify return type of `decryptPrivateKey()`

### ISSUE THREAD

**Issue by vsund** [ntzwrk/blockstack.ts#9]
The [`decryptPrivateKey()`](https://github.com/blockstack/blockstack.js/blob/286df82401c5be8d89e352054e2192e0f600ea98/src/auth/authMessages.js#L106) method in `src/auth/authMessages.js` should return a string according to its documentation.
But the method that's responsible for the return type, [`decryptECIES()`](https://github.com/blockstack/blockstack.js/blob/286df82401c5be8d89e352054e2192e0f600ea98/src/encryption.js#L105) can return a `string` or a `Buffer` (depending on whether `param2.wasString == true`).

I tried to trace the calls back and look whether it's supposed to be in there or not, but stopped at a [`decodeToken()` call](https://github.com/blockstack/blockstack.js/blob/b9d1bdcf618dcb7265ffd70d2946259f8f91b01a/src/auth/authApp.js#L155).

Should the method return a `string` in every case? If yes, is assured that `param2.wasString` is `true` in all calls?

**Comment by kantai** [comment]
No, it should be a `string` or `buffer` type

**Comment by vsund** [comment]
Thanks ;)
